# Generated by Django 3.1.2 on 2020-10-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Айди категории (короткое название, не отображается юзеру. Используется для добавления товаров в админке)')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, verbose_name='Название товара')),
                ('item_category', models.CharField(max_length=30, verbose_name='Категория товара (вводить короткое название категории, указанное в меню с категориями)')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='ТелеграмАйди')),
                ('status', models.CharField(max_length=20, verbose_name='Статус юзера')),
            ],
        ),
    ]
