# Generated by Django 3.1.2 on 2020-10-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0002_auto_20201020_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=30, verbose_name='Название товара')),
                ('item_category', models.CharField(max_length=100, verbose_name='Категория товара (вводить короткое название категории, указанное в разделе с категориями)')),
            ],
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
