# Generated by Django 3.1.2 on 2020-10-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0003_auto_20201020_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Название категории (отображается юзеру в боте)'),
            preserve_default=False,
        ),
    ]
