# Generated by Django 3.1.2 on 2020-10-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0004_auto_20201020_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(default=1, verbose_name='Цена товара в рублях (только целые числа)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=100, verbose_name='Айди категории (придумай короткое название (оно не отображается юзеру) для более удобного добавления товаров в админке. Может совпадать с первым параметром (отображаемым названием)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=50, verbose_name='Название категории (отображается юзеру в боте в разделе с выбором категории)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(verbose_name='ТелеграмАйди'),
        ),
    ]
